version: "3.9"
services:
  py3:
    build:
      context: ./py3
      dockerfile: Dockerfile
    # メモリのサイズを変える
    shm_size: '24gb'
    entrypoint: >
      tensorboard 
      --logdir ./logs

    expose:
      - "6006"
    #ここの左のポート番号を好きな値に設定 
    ports:
    - "6006:6006"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ./../data:/workspace
    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
